version: '3.7'
services:
    # container runs php fpm
    typo3:
        build:
          context: .
          args:
            - "PHP_VERSION=7.4.27"
            - "TYPO3_VERSION=11.5.6"
        container_name: typo3
        depends_on:
          - mysql
        restart: always
        volumes:
          - "./typo3/typo3conf:/var/www/typo3conf"
          #- "./typo3/typo3conf/LocalConfiguration.php:/var/www/typo3conf/LocalConfiguration.php"
        ports:
          - "80:80"
        networks:
          - php-net

    mysql:
      image: mysql:8.0
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
      environment:
        - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
        - "MYSQL_DATABASE=typo3"
      networks:
        - php-net

    mysql-init:
      image: mysql:8.0
      depends_on:
        - mysql
      environment:
        - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
        - "MYSQL_DATABASE=typo3"
      volumes:
        - "./typo3/typo3.sql:/tmp/typo3.sql" # admin & a1234sdf
      entrypoint: [ "bash", "-c", "sleep 10 && mysql --user=root --host=mysql --port=3306 typo3 < /tmp/typo3.sql && exit"]
      networks:
        - php-net

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
        - "8080:80"
      networks:
        - php-net
      environment:
        - "PMA_HOST=mysql"
        - "PMA_USER=root"
        - "PMA_PASSWORD="

networks:
  php-net:
    driver: bridge
